openapi: 3.0.0
info:
  title: Channels
  description: 'Streamline your communication through channels to collaborate across teams and get work done efficiently. Create channels for team discussions and organization-wide announcements and collaborate with clients and customers through external channels.<br><br>The Channels API allows you to create new channels, retrieve detailed information about specific channels, and fetch a list of channels the current user is a member of. It also enables you to manage channel participants by addin[...]'
  contact: {}
  version: 1.0.0
servers:
  -
    url: 'https://cliq.zoho.com/api/v2'
    description: 'API Endpoint'
tags:
  -
    name: channels
    description: 'Channels Module'
paths:
  '/channels':
    post:
      summary: Create a channel
      description: 'Use this API to create a new channel in Cliq.<br><br><b>Threshold limit</b> : 20 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
      deprecated: false
      security:
        - 
          Zoho_Auth:
            - ZohoCliq.Channels.CREATE
    get:
      summary: List all channels
      description: 'Retrieve a list of channels based on the given filters.<br><br><b>Threshold limit</b> : 30 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
      deprecated: false
      security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.READ     
  '/channels/{CHANNEL_ID}':
      get:
        summary: Retrieve a channel
        description: 'Use this API to get details of a specific channel.<br><br><b>Threshold limit</b> : 30 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
        deprecated: false
        security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.READ
      put:
        summary: Update a channel
        description: 'Use this API to get details of a specific channel.<br><br>You can also use this API to update the channel permissions.The members having higher level of role can edit the permissions of roles below them only if the member is having the permission to perform the particular action.<br><br><b>Threshold limit</b> : 50 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
        deprecated: false
        security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE
      delete:
        summary: Delete a channel
        description: 'Use this API to delete an existing channel.<br><br><b>Threshold limit</b> : 10 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
        deprecated: false
        security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.DELETE
  '/channels/{CHANNEL_ID}/members':
      get:
        summary: Get Channel Members
        description: 'Use this API to get the list of all members in a channel.<br><br><b>Threshold limit</b> : 100 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
        deprecated: false
        security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.READ  
      post:
        summary: Add Channel Members
        description: 'Use this API to add members in a channel, by giving their user id or their email ID.<br><br><b>Threshold limit</b> : 100 users per request can be added. 10 requests can be made per minute.<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
        deprecated: false
        security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE            
      delete:
        summary: Delete Channel Members
        description: 'Use this API to delete groups of members from the channel.<br><br><b>Threshold limit</b> : 100 users per request can be added. 10 requests can be made per minute.<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
        deprecated: false
        security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE        
  '/bots/{BOT_UNIQUE_NAME}/associate':
      post:                     
        summary: Add a Bot to a Channel
        description: 'Use this API to add a bot to a channel by providing its unique name.<br><br><b>Threshold limit</b> : 5 requests can be made per minute.<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
        deprecated: false
        security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE 
  '/channels/{CHANNEL_ID}/members/{USER_ID}/members':
    put:
      summary: Update a Channel member's role
      description: 'Use this API to add a bot to a channel by providing its unique name.<br><br><b>Threshold limit</b> : 10 requests can be made per minute.<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
      deprecated: false
      security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE 
  '/channels/{CHANNEL_ID}/approve':
    post:
      summary: Approve a Channel
      description: 'Organization admins can use this API to approve a newly created organization level channel.<br><br><b>Threshold limit</b> : 10 requests can be made per minute.<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
      deprecated: false
      security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE     
  '/channels/{CHANNEL_ID}/reject':
    post:
      summary: Reject a Channel
      description: 'Organization admins can use this API to reject a newly created organization level channel.<br><br><b>Threshold limit</b> : 10 requests can be made per minute.<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
      deprecated: false
      security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE               
  '/channels/{CHANNEL_ID}/join':
    post: 
      summary: Join a Channel
      description: 'Use this API to join a channel.<br><br><b>Threshold limit</b> : 10 requests can be made per minute.<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
      deprecated: false
      security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE   
  '/channels/{CHANNEL_ID}/leave':
    post: 
      summary: Leave a Channel
      description: 'Use this API to leave a channel.<br><br><b>Threshold limit</b> : 10 requests can be made per minute.<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
      deprecated: false
      security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE
  '/channels/{CHANNEL_ID}/archive':
    post: 
      summary: Archive a Channel
      description: 'Use this API to archive a channel.<br><br><b>Threshold limit</b> : 10 requests can be made per minute.<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
      deprecated: false
      security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE  
  '/channels/{CHANNEL_ID}/unarchive':
    post: 
      summary: Unarchive a Channel
      description: 'Use this API to unarchive a channel.<br><br><b>Threshold limit</b> : 10 requests can be made per minute.<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
      deprecated: false
      security:
            - 
              Zoho_Auth:
                - ZohoCliq.Channels.UPDATE                         

components:
  securitySchemes:
    Zoho_Auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth'
          scopes:
           ZohoCliq.Channels.CREATE: 'Create Channels'
           ZohoCliq.Channels.READ: 'Read Channels'
           ZohoCliq.Channels.UPDATE: 'Update Channels'
           ZohoCliq.Channels.DELETE: 'Delete Channels'




          

      

          

          

        

