openapi: 3.0.0
info:
  title: Messages
  description: 'The messaging API can be used to post message to a channel, user or a bot.The message structure can either be as simple as a text or customized as cards to serve different purposes.'
  contact: {}
  version: 1.0.0
servers:
  -
    url: 'https://cliq.zoho.com/api/v2'
    description: 'API Endpoint'
tags:
  -
    name: messages
    description: 'Messages Module'
paths:
  '/chats/{CHAT_ID}/messages':
    get:
      summary: Get Messages
      description: 'Retrieves messages from a chat conversation that the user has access to.<br><br><b>Threshold limit</b> : 15 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>'
      deprecated: false
      security:
        - 
          Zoho_Auth:
            - ZohoCliq.Messages.READ
  '/chats/{CHAT_ID}/messages/{MESSAGE_ID}/messages':
    get:
      summary: Retrieve a message
      description: "Use this API to retrieve a message from a chat conversation that you have access to. Get the message's unique ID by calling the get messages API.<br><br><b>Threshold limit</b> : 30 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>"
      deprecated: false
      security:
        - 
          Zoho_Auth:
            - ZohoCliq.Messages.READ
  '/channelsbyname/{CHANNEL_UNIQUE_NAME}/message':
    post:
      summary: Post message in a channel
      description: "You can post a message in a channel using its unique name. The message can be simple text or a message card with buttons. To find the channel's unique name, select the <b>View Information</b> option in the channel preview and then click on <b>Connectors</b>. The API endpoint will display the channel's unique name.<br><br><b>Threshold limit</b> : 50 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 10 minutes<br>Wait time befo[...]"
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoCliq.Webhooks.CREATE  
  '/bots/{BOT_UNIQUE_NAME}/message': 
    post: 
      summary: Post message to a bot
      description: "You can send a message to a bot using its unique name. The message can be a simple text or a message card with buttons. You can obtain the bot's unique name from its API endpoint URL. To find the API endpoint URL and bot's unique name, go to Bots & Tools → Bots → Click on the bot of your choice → Copy the API endpoint URL and the bot unique name from the URL.<br><br><b>Threshold limit</b> : 50 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b[...]"
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoCliq.Webhooks.CREATE
  '/chats/{CHAT_ID}/message':
    post: 
      summary: Post message in chat
      description: "To post message in a chat (or thread), the chat_id (thread_id in case of threads) can be used in the request URL.<br><br>The message can be a simple text as well as a message card with buttons. Take a look at our message cards.<br><br><b>Threshold limit</b> : 50 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 10 minutes<br>Wait time before consecutive API requests.<br>"
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoCliq.Webhooks.CREATE
  '/buddies/{EMAIL_ID}/message':
    post: 
      summary: Post message to a user
      description: "Post a message to a user by giving the email ID in the request URL, followed by the message object containing plain text or message card.<br><br>The zuid of the user can also be given instead of the email ID.<br><br>Note: This API will be not applicable if the intended user is neither a mutual contact nor your organization member.<br><br><b>Threshold limit</b> : 50 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 10 minutes<[...]"
      
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoCliq.Webhooks.CREATE

  '/chats/{CHAT_ID}/messages/{MESSAGE_ID}':
    put:
      summary: Edit a message
      description: "Use this API to edit a message in a conversation. Get the message's unique ID by using the get messages API.<br><br><b>Threshold limit</b> : 50 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 10 minutes<br>Wait time before consecutive API requests.<br>"

      deprecated: false

      security:
        -
          Zoho_Auth:
            - ZohoCliq.Webhooks.UPDATE 

    delete:
      summary: Delete a message
      description: "Use this API to delete a message in a conversation. Get the message's unique ID by using the get messages API.<br><br><b>Threshold limit</b> : 20 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>"
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoCliq.Webhooks.DELETE  
  '/chats/{CHAT_ID}/messages/{MESSAGE_ID}/reactions':
    get:
      summary: Get Reactions
      description: "Use this API to retrieve details for all reactions to a specific message.<br><br><b>Threshold limit</b> : 50 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 10 minutes<br>Wait time before consecutive API requests.<br>"
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoCliq.messageactions.READ
    post:
      summary: Add a reaction
      description: "Use this API to add a react to a message sent in a chat. Get the message's unique ID by using the get messages API.<br><br><b>Threshold limit</b> : 20 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>"

      deprecated: false

      security:
        -
          Zoho_Auth:
            - ZohoCliq.messageactions.CREATE

    delete:
      summary: Delete a reaction
      description: "Use this API to delete the reaction to a message.<br><br><b>Threshold limit</b> : 20 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>"
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoCliq.messageactions.CREATE        
components:
  securitySchemes:
    Zoho_Auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth'
          scopes:
            ZohoCliq.Messages.READ: 'Read Messages'
            ZohoCliq.Messages.UPDATE: 'Update Messages'
            ZohoCliq.Messages.DELETE: 'Delete Messages'
            ZohoCliq.Webhooks.CREATE: 'Post messages to your conversations directly or by using incoming webhooks'
            ZohoCliq.messageactions.READ: 'Access message actions'
            ZohoCliq.messageactions.CREATE: 'Create message actions'
            ZohoCliq.messageactions.DELETE: 'Delete message actions'




          

      

          

          

        

