openapi: 3.0.0
info:
  title: Reminders
  description: >
    Cliq's reminders help you keep track of essential tasks that you need to complete but don't want to forget.<br><br>
    
    They make micromanaging your tasks effortless. With these APIs, you can create, edit, and mark reminders as complete or incomplete, snooze, retrieve, and assign users to specific reminders.<br><br>
    
    You can create and assign reminders to yourself, a teammate or colleague, a chat, or a channel. Additionally, you can set a specific message in a chat as a reminder. Each type of reminder requires its own set of parameters to be included in the request body.
  contact: {}
  version: 1.0.0

servers:
  - url: 'https://cliq.zoho.com/api/v2'
    description: 'API Endpoint'

tags:
  - name: reminders
    description: 'Reminders Module'

paths:
  /reminders:
    post:
      summary: Set a self reminder
      description: >
        Use this API to set a self reminder.
        <br><br>
        <b>Threshold limit</b>: 50 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
        - Zoho_Auth:
            - ZohoCliq.Reminders.CREATE
            - ZohoCliq.Reminders.ALL

    get:  
      summary: Get list of all reminders
      description: |
        Use this API to retrieve details for all reminders. If no specific category is indicated, the API will return a list of reminders under the default category "mine." By default, the API provides a list of 20 reminders.<br><br>
        <b>next_set_token</b>: This token will be issued in two scenarios:
        <ol>
        <li>If no limit is specified and there are more than 20 reminders in your list.</li>
        <li>If you set a limit on the number of reminders to be retrieved, the token will be provided to access the next set of reminders. Please note that the token will be given only if the total number of reminders exceeds the limit you specified.</li>
        </ol>
        <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>Wait time before consecutive API requests.<br>
      security:
        - Zoho_Auth:
            - ZohoCliq.Reminders.CREATE
            - ZohoCliq.Reminders.ALL


  /reminders/{REMINDER_ID}:
    get:
      summary: Retrieve a reminder
      description: |
       Use this API to obtain details of a specific reminder by providing the reminder ID in the query. You can retrieve the reminder ID from the API's response that lists all reminders.<br><br>
       <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
        - Zoho_Auth:
            - ZohoCliq.Reminders.READ
            - ZohoCliq.Reminders.ALL      

    put:
      summary: Update a reminder
      description: |
       Use this API to edit the details of a specific reminder by providing the reminder ID. You can obtain the reminder ID from the API's response that lists all reminders.<br><br>
       <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Reminders.UPDATE
              - ZohoCliq.Reminders.ALL      

    delete:
      summary: Delete a reminder
      description: |
       Use this API to delete a particular reminder by giving the reminder ID. You can obtain the reminder ID from the API's response that lists all reminders.<br><br>
       <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Reminders.DELETE
              - ZohoCliq.Reminders.ALL 

  /reminders/batch:
    delete:
      summary: Delete Reminders
      description: |
        Use this API to delete a list of reminders by providing the reminder IDs. You can obtain the reminder ID from the API's response that lists all reminders.<br><br>
        <b>Note</b>: The maximum number of reminders that can be deleted at once is 20.<br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
          Number of API calls allowed within a minute.<br><br>

          <b>Lock period</b>: 10 minutes<br>
          Wait time before consecutive API requests.

      security:
            - Zoho_Auth:
                - ZohoCliq.Reminders.DELETE
                - ZohoCliq.Reminders.ALL 

  /reminders/clearcompleted:
    delete:
      summary: Delete completed reminders
      description: |
        Use this API to delete the list of reminders that are marked as complete.<br><br>
        <b>Threshold limit</b>: 10 requests per min per user<br>
          Number of API calls allowed within a minute.<br><br>

          <b>Lock period</b>: 10 minutes<br>
          Wait time before consecutive API requests.

      security:
            - Zoho_Auth:
                - ZohoCliq.Reminders.UPDATE
                - ZohoCliq.Reminders.ALL 

  /reminders/{REMINDER_ID}/complete:
    put:
      summary: Mark a reminder as complete
      description: |
        Use this API to mark a reminder as complete by providing the reminder ID.<br><br>
        <b>Note</b>: Reminders set for yourself (i.e falling under the mine category) can be marked as complete or incomplete.<br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
          Number of API calls allowed within a minute.<br><br>

          <b>Lock period</b>: 10 minutes<br>
          Wait time before consecutive API requests.

      security:
            - Zoho_Auth:
                - ZohoCliq.Reminders.UPDATE
                - ZohoCliq.Reminders.ALL   

  /reminders/{REMINDER_ID}/incomplete:
    put:
      summary: Mark a reminder as incomplete
      description: |
        Use this API to mark a reminder as incomplete by providing the reminder ID.<br><br>
        <b>Note</b>: Reminders set for yourself (i.e falling under the mine category) can be marked as complete or incomplete.<br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
          Number of API calls allowed within a minute.<br><br>

          <b>Lock period</b>: 10 minutes<br>
          Wait time before consecutive API requests.

      security:
            - Zoho_Auth:
                - ZohoCliq.Reminders.UPDATE
                - ZohoCliq.Reminders.ALL   

  
  /reminders/{REMINDER_ID}/snooze:
    put:
      summary: Snooze a reminder
      description: |
        Use this API to snooze a reminder by providing the reminder ID.<br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
          Number of API calls allowed within a minute.<br><br>

          <b>Lock period</b>: 10 minutes<br>
          Wait time before consecutive API requests.

      security:
            - Zoho_Auth:
                - ZohoCliq.Reminders.UPDATE
                - ZohoCliq.Reminders.ALL                 

  /reminders/{REMINDER_ID}/dismisssnooze:
    put:
      summary: Dismiss a snoozed reminder
      description: |
        Use this API to dismiss a snoozed reminder by providing the reminder ID.<br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
          Number of API calls allowed within a minute.<br><br>

          <b>Lock period</b>: 10 minutes<br>
          Wait time before consecutive API requests.

      security:
            - Zoho_Auth:
                - ZohoCliq.Reminders.UPDATE
                - ZohoCliq.Reminders.ALL   

  /reminders/{REMINDER_ID}/users:
    post:
      summary: Assign users to a reminder
      description: |
        Use this API to assign users to reminders. A maximum of 4 users can be assigned to a reminder.<br><br>
        <b>Note</b>: This API will only work with reminders added in the Others category, i.e. reminders assigned by you to others.<br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
          Number of API calls allowed within a minute.<br><br>

          <b>Lock period</b>: 10 minutes<br>
          Wait time before consecutive API requests.

      security:
            - Zoho_Auth:
                - ZohoCliq.Reminders.UPDATE
                - ZohoCliq.Reminders.ALL  

  /reminders/{REMINDER_ID}/users/{USER_ID}:
    delete:
      summary: Unassign a user from a reminder
      description: |
        Use this API to unassign users from a reminder, by providing their User ID.<br><br>
        <b>Note</b>: This API will work with reminders added in the Others category, i.e. reminders assigned by you to others.<br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
          Number of API calls allowed within a minute.<br><br>

          <b>Lock period</b>: 10 minutes<br>
          Wait time before consecutive API requests.

      security:
            - Zoho_Auth:
                - ZohoCliq.Reminders.UPDATE
                - ZohoCliq.Reminders.ALL  

  /reminders/{REMINDER_ID}/users/{USER_ID}/remind:
    put:
      summary: Remind assignee
      description: |
        Use this API to trigger a notification in Taz to a particular assignee who is yet to mark the reminder as complete.<br><br>
        <b>Note</b>: This API will work with reminders added in the Others category, i.e. reminders assigned by you to others.<br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
          Number of API calls allowed within a minute.<br><br>

          <b>Lock period</b>: 10 minutes<br>
          Wait time before consecutive API requests.

      security:
            - Zoho_Auth:
                - ZohoCliq.Reminders.UPDATE
                - ZohoCliq.Reminders.ALL  

  /reminders/{REMINDER_ID}/remind:
    post:
      summary: Remind assignees
      description: |
        Use this API to trigger a notification in Taz to a reminder's assignees who are yet to mark the reminder as complete.<br><br>
        <b>Note</b>: This API will only work with reminders added in the Others category, i.e. reminders assigned by you to others.<br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
            - Zoho_Auth:
                - ZohoCliq.Reminders.UPDATE
                - ZohoCliq.Reminders.ALL  

                
components:
  securitySchemes:
    Zoho_Auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth'
          scopes:
            ZohoCliq.Reminders.CREATE: Create Reminders
            ZohoCliq.Reminders.ALL: Create , Read , Update and Manage reminders