openapi: 3.0.0
info:
  title: Roles
  description: >
    You can set up roles for a group of users and configure distinct access permissions for various features in Zoho Cliq.
    However, you must be an admin to access these APIs.

  contact: {}
  version: 1.0.0

servers:
  - url: 'https://cliq.zoho.com/api/v2'
    description: 'API Endpoint'

tags:
  - name: roles
    description: 'Roles Module'

paths:
  /profiles:
    get:
      summary: Get Roles
      description: |
        Use this API to fetch all available roles in your organization
        <br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.<br><br>

      security:
        - Zoho_Auth:
            - ZohoCliq.Organisation.READ


    post:
      summary: Create a Role
      description: |
        Use this API to create a custom role in your organization.
        <br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Organisation.CREATE

  /profiles/{PROFILE_ID}:
    get:
      summary: Retrieve role details
      description: |
        Use this API to retrieve detailed information about a specific role.
        <br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Organisation.READ

    put:
      summary: Edit a Role
      description: |
        Use this API to update a role in your organization.
        <br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Organisation.UPDATE

    delete:
      summary: Delete a Role
      description: |
        Use this API to delete a role in your organization.
        <br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Organisation.DELETE

  /profiles/{PROFILE_ID}/permissions:
    get:
      summary: Get permissions of a role
      description: |
        Use this API to get the permissions of a role in your organization.
        <br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Organisation.READ

    put:
      summary: Update permissions of a role
      description: |
        Use this API to update a role in your organization.
        <br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Organisation.UPDATE  

  /profiles/{PROFILE_ID}/users:
    get:
      summary: Get users in a role
      description: |
        Use this API to get all the users in a specific role.
        <br><br>
        <b>Threshold limit</b>: 30 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Organisation.READ  

    post:
      summary: Add users to a role
      description: |
        Use this API to add users to a specific role.
        <br><br>
        <b>Threshold limit</b>: 10 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Organisation.UPDATE  

    delete:
      summary: Delete users from a role
      description: |
        Use this API to delete users from a specific role.
        <br><br>
        <b>Threshold limit</b>: 10 requests per min per user<br>
        Number of API calls allowed within a minute.<br><br>

        <b>Lock period</b>: 10 minutes<br>
        Wait time before consecutive API requests.

      security:
          - Zoho_Auth:
              - ZohoCliq.Organisation.DELETE  


components:
  securitySchemes:
    Zoho_Auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth'
          scopes:
            ZohoCliq.Organisation.CREATE: Add Roles in an Organization
            ZohoCliq.Organisation.UPDATE: Update Roles in an Organization
            ZohoCliq.Organisation.DELETE: Delete Roles in an Organization
            ZohoCliq.Organisation.READ: Read Roles in an Organization