openapi: 3.0.0
info:
  title: Threads
  description: >
    Threads are a new way to organize discussions in a channel by grouping messages by specific topics.
    With threads, replies to channel messages can be organized in separate spaces.

    You can use the Threads API to create threads, send messages, get and manage thread followers,
    manage the thread's state (reopening or closing it), and retrieve threads from a specific channel,
    among other functionalities.
  contact: {}
  version: 1.0.0

servers:
  - url: 'https://cliq.zoho.com/api/v2'
    description: 'API Endpoint'

tags:
  - name: threads
    description: 'Threads Module'

paths:
  /channels/{CHANNEL_ID}/message:
    post:
      summary: Create and send a thread message
      description: >
        Use this API to create a thread from a message sent in a channel.

        **Threshold limit**: 50 requests per min per user  
        Number of API calls allowed within a minute.

        **Lock period**: 5 minutes  
        Wait time before consecutive API requests.
      security:
        - Zoho_Auth:
            - ZohoCliq.Webhooks.CREATE

  /chats/{THREAD_CHAT_ID}/message:
    post:
      summary: Send a message to an existing thread
      description: |
            Use this API to send a message to an existing thread.
            <ul>
            <li>Use the <b>Retrieve Message API</b> to obtain the thread details.</li>
            
            <li>The response from the <b>Retrieve Message API</b> includes a <code>`thread_information`</code> object containing the <code>`chat_id`</code>.</li>
           
            <li>Use this <code>`chat_id`</code> as the <b>Thread Chat ID</b> for all thread-related API endpoints.</li>
            </ul>
            <br>
            <b><u>Example response from Retrieve Message API:</u></b>
            <br>
            <code>
            {
              "sender": {
                "name": "Scott Fisher",
                "id": "12345678"
              },
              "id": "1629465328414_83277101498",
              "time": 1629465328414,
              "type": "text",
              "content": {
                "text": "Hello Guys!"
              },
              "thread_information": {
                "is_follower": true,
                "message_count": 19,
                "follower_count": 2,
                "thread_message_id": "1629426730589%2040288830613",
                "title": "Daily Updates",
                "chat_id": "CT_1256254372211218512_15067887-T-1256254377053952763"
              }
            }
            </code>
      security:
        - Zoho_Auth:
            - ZohoCliq.Webhooks.CREATE
  /channels/{CHANNEL_ID}/threads:
    get:
      summary: Get threads of a channel
      description: Use this API to retrieve all the threads in a chat.
      security:
        - Zoho_Auth:
            - ZohoCliq.Chats.READ
  /channels/{CHANNEL_ID}: 
    put:
      summary: Auto follow
      description: "Use this API to auto-follow all threads created in a channel..<br><br><b>Threshold limit</b> : 50 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>"
      security:
        - Zoho_Auth:
            - ZohoCliq.Channels.UPDATE
  /threads/{THREAD_CHAT_ID}/followers:
    get:
      summary: Get thread followers
      description: "Use this API to get the followers of the thread.<br><br><b>Threshold limit</b> : 20 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>"
      security:
        - Zoho_Auth:
            - ZohoCliq.Chats.READ    
    post:
      summary: Add followers to a thread
      description: "Use this API to add one or more users as followers to an existing thread.<br><br><b>Threshold limit</b> : 20 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>"
      security:
        - Zoho_Auth:
            - ZohoCliq.Chats.UPDATE   

    delete:
      summary: Remove followers from a thread
      description: Removes one or more specified users from the followers list of a given thread.
      security:
        - Zoho_Auth:
            - ZohoCliq.Chats.DELETE  

  /threads/{THREAD_CHAT_ID}/nonfollowers:
    get:
      summary: Get non-followers of a thread
      description: "Use this API to retrieve the list of channel members who are not currently following the specified thread.<br><br><b>Threshold limit</b> : 20 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>"
      security:
        - Zoho_Auth:
            - ZohoCliq.Chats.READ              

  /threads/{THREAD_CHAT_ID}/follow:
      post:
        summary: Join (follow) a thread
        description: Allows the authenticated user to join a thread as a follower
        security:
        - Zoho_Auth:
            - ZohoCliq.Chats.UPDATE    

  /threads/{THREAD_CHAT_ID}/unfollow:
      post:
        summary: Leave (unfollow) a thread
        description: Allows the authenticated user to leave a thread they are currently following.
        security:
        - Zoho_Auth:
            - ZohoCliq.Chats.UPDATE               

  /threads/{THREAD_CHAT_ID}:
    put:    
      summary: Update the state of a thread
      description: "Use this API to close or reopen a thread. This can be performed by a user or by a bot.<br><br><b>Threshold limit</b> : 20 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>"
      security:
        - Zoho_Auth:      
            - ZohoCliq.Chats.UPDATE

  /threads/{THREAD_CHAT_ID}/messages/main:
    get:
      summary: Get main message of a thread
      description: "Use this API to retrieve the main message from which the thread was created.<br><br><b>Threshold limit</b> : 30 requests per min per user<br>Number of API calls allowed within a minute.<br><br><b>Lock period</b>: 5 minutes<br>Wait time before consecutive API requests.<br>"
      security:
        - Zoho_Auth:      
            - ZohoCliq.Messages.READ

components:
  securitySchemes:
    Zoho_Auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth'
          scopes:
            ZohoCliq.Webhooks.CREATE: Post messages to your conversations directly or by using incoming webhooks
            ZohoCliq.Chats.UPDATE: Modify Chats
            ZohoCliq.Chats.DELETE: Delete Chats
